Update sync-with-master.yml

diff --git a/.github/workflows/sync-with-master.yml b/.github/workflows/sync-with-master.yml
--- a/.github/workflows/sync-with-master.yml
+++ b/.github/workflows/sync-with-master.yml
@@ -53,7 +53,7 @@ jobs:
 
           echo "Get latest merged PR details"
           echo "=========================================================="
-          LATEST_PR_SHA=b30dd18094005951eccd3ff603bad27dd3560612
+          LATEST_PR_SHA=de15dfe8388
           MERGED_PR=$(curl -s "https://api.github.com/search/issues?q=${LATEST_PR_SHA}+type:pr+is:merged+base:master")
           PR_NUMBER=$(echo $MERGED_PR | jq -r '.items[0].number')
           PR_URL=$(echo $MERGED_PR | jq -r '.items[0].html_url')
@@ -84,7 +84,7 @@ jobs:
           git config --global user.name ${GIT_USERNAME}
           for commit in $PR_COMMITS_SHA
           do
-            git cherry-pick $commit
+            git cherry-pick $commit || true
           done
           echo ""
 
@@ -106,6 +106,20 @@ jobs:
           -d '{ "title": "'"${TITLE}"'","body": "'"${BODY}"'","head": "'"${{ env.GIT_USERNAME }}:${{ env.SYNCHRONIZE_BRANCH_NAME }}"'","base":"'"${{ env.TARGET_BRANCH_NAME }}"'"}')
           RESPONSE_BODY=${RESPONSE::-3}
           STATUS=$(printf "%s" "$RESPONSE" | tail -c 3)
-          if [[ $STATUS == "201" ]]; then
-            echo $RESPONSE_BODY | jq -r '.html_url'
+          if [[ $STATUS != "201" ]]; then
+            echo "Error while creating the PR"
+            echo $RESPONSE_BODY
+            exit 1
           fi
+          echo "PR created successfully"
+          echo $RESPONSE_BODY | jq -r '.html_url'
+          PR_NUMBER=$(echo "${RESPONSE_BODY}" | jq -r '.number')
+          
+          echo 'Add comment to the PR'
+          echo "=========================================================="
+          COMMENT_BODY="Hi @${PR_USER}, please review and merge this PR."
+          RESPONSE=$(curl -s -w "%{http_code}" -k -X \
+          POST https://api.github.com/repos/${{ env.PRODUCT_REPOSITORY_PUBLIC }}/issues/${PR_NUMBER}/comments \
+          -H "Authorization: Bearer "${{ secrets.PAT }}"" \
+          -H "Content-Type: application/json" \
+          -d '{ "body": "'"${COMMENT_BODY}"'"}')
